#!/usr/bin/zsh
colors_file="$HOME/.cache/wal/colors.sh"
output_file="$HOME/.cache/wal/hyprland-styles.conf"
source "$colors_file"
function hex_to_rgba() {
    local hex="${1:l}"
    local rgba_hex="${hex:1}ff"
    printf "rgba(%s)\n" "$rgba_hex"
}
echo "# Hyprland-compatible styles" > "$output_file"
echo "\$wallpaper = $wallpaper" >> "$output_file"
echo "\$background = $(hex_to_rgba $background)" >> "$output_file"
echo "\$foreground = $(hex_to_rgba $foreground)" >> "$output_file"
echo "\$cursor = $(hex_to_rgba $cursor)" >> "$output_file"
echo "\$color0 = $(hex_to_rgba $color0)" >> "$output_file"
echo "\$color1 = $(hex_to_rgba $color1)" >> "$output_file"
echo "\$color2 = $(hex_to_rgba $color2)" >> "$output_file"
echo "\$color3 = $(hex_to_rgba $color3)" >> "$output_file"
echo "\$color4 = $(hex_to_rgba $color4)" >> "$output_file"
echo "\$color5 = $(hex_to_rgba $color5)" >> "$output_file"
echo "\$color6 = $(hex_to_rgba $color6)" >> "$output_file"
echo "\$color7 = $(hex_to_rgba $color7)" >> "$output_file"
echo "\$color8 = $(hex_to_rgba $color8)" >> "$output_file"
echo "\$color9 = $(hex_to_rgba $color9)" >> "$output_file"
echo "\$color10 = $(hex_to_rgba $color10)" >> "$output_file"
echo "\$color11 = $(hex_to_rgba $color11)" >> "$output_file"
echo "\$color12 = $(hex_to_rgba $color12)" >> "$output_file"
echo "\$color13 = $(hex_to_rgba $color13)" >> "$output_file"
echo "\$color14 = $(hex_to_rgba $color14)" >> "$output_file"
echo "\$color15 = $(hex_to_rgba $color15)" >> "$output_file"
